# Generated by Django 2.2.1 on 2019-06-17 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchid', models.IntegerField()),
                ('season', models.IntegerField()),
                ('city', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('team1', models.CharField(max_length=128)),
                ('team2', models.CharField(max_length=128)),
                ('toss', models.CharField(max_length=128)),
                ('toss_decision', models.CharField(max_length=128)),
                ('result', models.CharField(max_length=128)),
                ('dl_applied', models.IntegerField()),
                ('winner', models.CharField(max_length=128)),
                ('win_by_runs', models.IntegerField()),
                ('win_by_wickets', models.IntegerField()),
                ('mom', models.CharField(max_length=128)),
                ('venue', models.CharField(max_length=128)),
                ('umpire1', models.CharField(max_length=128)),
                ('umpire2', models.CharField(max_length=128)),
                ('umpire3', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inning', models.IntegerField()),
                ('bat_team', models.IntegerField()),
                ('bowl_team', models.IntegerField()),
                ('over', models.IntegerField()),
                ('ball', models.IntegerField()),
                ('striker', models.CharField(max_length=128)),
                ('non_striker', models.CharField(max_length=128)),
                ('bowler', models.CharField(max_length=128)),
                ('is_super_over', models.IntegerField()),
                ('wide_runs', models.IntegerField()),
                ('bye_runs', models.IntegerField()),
                ('leg_byes', models.IntegerField()),
                ('noball_runs', models.IntegerField()),
                ('penalty', models.IntegerField()),
                ('batsman_runs', models.IntegerField()),
                ('extras', models.IntegerField()),
                ('total_runs', models.IntegerField()),
                ('player_dismissed', models.CharField(max_length=128)),
                ('dismissal_kind', models.CharField(max_length=128)),
                ('fielder', models.CharField(max_length=128)),
                ('matchid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iplapp.Matches')),
            ],
        ),
    ]
