# Generated by Django 2.2.1 on 2019-06-17 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0002_auto_20190617_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='city',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
