# Generated by Django 2.2.1 on 2019-06-17 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0005_auto_20190617_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliveries',
            old_name='matchid',
            new_name='match_id',
        ),
    ]
